// <auto-generated />
using System;
using FinanceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("FinanceAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pagamento",
                            Type = "entrada"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Recebidos",
                            Type = "entrada"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vale alimentação",
                            Type = "entrada"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Necessidades",
                            Type = "saida"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Contas",
                            Type = "saida"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mercado",
                            Type = "saida"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Aluguel",
                            Type = "saida"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Restaurante",
                            Type = "saida"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Assinaturas",
                            Type = "saida"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Educação",
                            Type = "saida"
                        });
                });

            modelBuilder.Entity("FinanceAPI.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinanceAPI.Models.Transaction", b =>
                {
                    b.HasOne("FinanceAPI.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceAPI.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
