### GET LISTAR TODAS AS TRANSACOES
GET http://localhost:5000/api/transactions


### POST cadastrar uma transacao

POST http://localhost:5000/api/transactions
Content-Type: application/json

{
    "description": "Salário",
    "amount": 3500,
    "date": "2025-04-25T00:00:00",
    "type": "entrada",
    "categoryId": 1,
    "userId": 3
}