### GET LISTAR TODAS AS TRANSACOES
GET http://localhost:5000/api/transactions

### GET LISTAR SOMENTE DO USUARIO
GET http://localhost:5000/api/transactions/user/2


### POST cadastrar uma transacao

POST http://localhost:5000/api/transactions
Content-Type: application/json

{
  "description": "OutBack",
  "amount": 500.00,
  "date": "2025-04-25T00:00:00",
  "type": "Saida",
  "categoryId": 5,
  "userId": 2  
}

### DELETE da transacao id e depois id do user

DELETE http://localhost:5000/api/transactions/6/user/3