### GET LISTAR usuario
GET http://localhost:5000/api/users

### POST cadastrar usuario

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "Name": "Zelaide",
    "Password": "1234"
}

### PUT atualizar o usuario

PUT http://localhost:5000/api/users/3
Content-Type: application/json

{
    "Name": "Anabelle",
    "Password": "12345"
}

### POST LOGIN DO USUARIO

POST  http://localhost:5000/api/users/login
Content-Type: application/json

{
    "Name": "Bruna",
    "Password": "1234"
}


### Deletar o usuario

DELETE  http://localhost:5000/api/users/4
Content-Type: application/json

{

}
