### ============================
### CATEGORIAS
### ============================

### [GET] Listar todas as categorias
GET http://localhost:5000/api/categories


###

### [POST] Criar uma nova categoria
POST http://localhost:5000/api/categories
Content-Type: application/json

{
  "name": "Educação"
}

###

### [DELETE] Remover uma categoria por ID
DELETE http://localhost:5000/api/categories/1
