### GET LISTAR TODAS AS TRANSACOES
GET http://localhost:5000/api/transactions




### GET LISTAR SOMENTE AS TRANSÇÃO DE UM USUARIO ESPECÍFICO
GET http://localhost:5000/api/transactions/user/1


### POST cadastrar uma transacao

POST http://localhost:5000/api/transactions
Content-Type: application/json

{
  "description": "Iphone 14",
  "amount": 7000.00,
  "date": "2025-04-25T00:00:00",
  "type": "Saida",
  "categoryId": 2,
  "UserId": 1  
}

### DELETE da transacao id e depois id do user

DELETE http://localhost:5000/api/transactions/4/user/1