### TRANSAÇÕES

### [GET] Listar todas as transações com categorias
GET http://localhost:5000/api/transactions


###

### [GET] Obter transação por ID
GET http://localhost:5000/api/transactions/8


###

### [POST] Criar nova transação
POST http://localhost:5000/api/transactions
Content-Type: application/json

{
  "description": "Curso de inglês",
  "amount": 200.00,
  "type": "Saída",
  "categoryId": 2
}

###

### [PUT] Atualizar transação existente (ID = 1)
PUT http://localhost:5000/api/transactions/1
Content-Type: application/json

{
  "description": "Curso de inglês - atualização",
  "amount": 180.00,
  "date": "2025-05-30T00:00:00",
  "type": "Saída",
  "categoryId": 1
}

###

### [DELETE] Remover uma transação por ID
DELETE http://localhost:5000/api/transactions/6
